/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target, mod));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => EmbedCodeFile
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");

// settings.ts
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  includedLanguages: "c,cpp,java,python,go,ruby,javascript,js,typescript,ts,shell,sh,bash",
  titleBackgroundColor: "#00000020",
  titleFontColor: "",
  wrapCodeBlock: false,
  showLineNumbers: false
};
var EmbedCodeFileSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app2, plugin) {
    super(app2, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Embed Code File Settings" });
    new import_obsidian.Setting(containerEl).setName("Included Languages").setDesc("Comma separated list of included languages.").addText((text) => text.setPlaceholder("Comma separated list").setValue(this.plugin.settings.includedLanguages).onChange(async (value) => {
      this.plugin.settings.includedLanguages = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Font color of title").addText((text) => text.setPlaceholder("Enter a color").setValue(this.plugin.settings.titleFontColor).onChange(async (value) => {
      this.plugin.settings.titleFontColor = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Background color of title").addText((text) => text.setPlaceholder("#00000020").setValue(this.plugin.settings.titleBackgroundColor).onChange(async (value) => {
      this.plugin.settings.titleBackgroundColor = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Wrap code blocks").setDesc("With this option enabled, embedded code files will wrap long lines.").addToggle((toggle) => toggle.setValue(this.plugin.settings.wrapCodeBlock).onChange(async (value) => {
      this.plugin.settings.wrapCodeBlock = value;
      await this.plugin.saveSettings();
      const view = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
      view?.previewMode.rerender(true);
    }));
    new import_obsidian.Setting(containerEl).setName("Show line numbers").setDesc("With this option enabled, embedded code files will show original source line numbers.").addToggle((toggle) => toggle.setValue(this.plugin.settings.showLineNumbers).onChange(async (value) => {
      this.plugin.settings.showLineNumbers = value;
      await this.plugin.saveSettings();
      const view = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
      view?.previewMode.rerender(true);
    }));
  }
};

// utils.ts
var import_path = __toESM(require("path"));
function analyseSrcLines(str) {
  str = str.replace(/\s*/g, "");
  const result = [];
  let strs = str.split(",");
  strs.forEach((it) => {
    if (/\w+-\w+/.test(it)) {
      let left = Number(it.split("-")[0]);
      let right = Number(it.split("-")[1]);
      for (let i = left; i <= right; i++) {
        result.push(i);
      }
      result.push(0);
    } else {
      result.push(Number(it));
      result.push(0);
    }
  });
  return result;
}
function extractSrcLines(fullSrc, srcLinesNum) {
  let src = "";
  const fullSrcLines = fullSrc.split("\n");
  const fullSrcLinesLen = fullSrcLines.length;
  srcLinesNum.forEach((lineNum, index, arr) => {
    if (lineNum > fullSrcLinesLen) {
      arr.splice(index, 1);
    }
  });
  srcLinesNum.forEach((lineNum, index, arr) => {
    if (lineNum == 0 && arr[index - 1] == 0) {
      arr.splice(index, 1);
    }
  });
  srcLinesNum.forEach((lineNum, index) => {
    if (lineNum > fullSrcLinesLen) {
      return;
    }
    if (index == srcLinesNum.length - 1 && lineNum == 0 && srcLinesNum[index - 1] == fullSrcLinesLen) {
      return;
    }
    if (index == 0 && lineNum != 1) {
      src = "...\n" + fullSrcLines[lineNum - 1];
      return;
    }
    if (lineNum == 0) {
      src = src + "\n...";
      return;
    }
    if (index == 0) {
      src = fullSrcLines[lineNum - 1];
    } else {
      src = src + "\n" + fullSrcLines[lineNum - 1];
    }
  });
  return src;
}
function sourceLineNumbers(fullSrc, srcLinesNum) {
  const fullSrcLinesLen = fullSrc.split("\n").length;
  if (srcLinesNum.length == 0) {
    return Array.from({ length: fullSrcLinesLen }, (_, index) => String(index + 1));
  }
  const compactLineNums = [];
  srcLinesNum.forEach((lineNum) => {
    if (lineNum > fullSrcLinesLen) {
      return;
    }
    if (lineNum == 0 && compactLineNums[compactLineNums.length - 1] == 0) {
      return;
    }
    compactLineNums.push(lineNum);
  });
  const lineNumbers = [];
  compactLineNums.forEach((lineNum, index) => {
    if (index == compactLineNums.length - 1 && lineNum == 0 && compactLineNums[index - 1] == fullSrcLinesLen) {
      return;
    }
    if (index == 0 && lineNum != 1) {
      lineNumbers.push("");
      lineNumbers.push(String(lineNum));
      return;
    }
    if (lineNum == 0) {
      lineNumbers.push("");
      return;
    }
    lineNumbers.push(String(lineNum));
  });
  return lineNumbers;
}
function normalizeCommentStyle(style) {
  const value = String(style ?? "above").trim().toLowerCase();
  return ["above", "inline", "icon"].includes(value) ? value : "above";
}
function normalizeCommentText(comment) {
  if (Array.isArray(comment)) {
    return comment.map((item) => normalizeCommentText(item)).join("\n");
  }
  if (comment == null) {
    return "";
  }
  return String(comment);
}
function escapeHtmlAttribute(value) {
  return String(value).replace(/&/g, "&amp;").replace(/"/g, "&quot;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}
function dedentLocalFootnoteLines(lines) {
  const minIndent = lines.reduce((min, line) => {
    if (!line.trim()) {
      return min;
    }
    const indent = line.match(/^\s*/)?.[0].length ?? 0;
    return Math.min(min, indent);
  }, Infinity);
  if (!Number.isFinite(minIndent) || minIndent === 0) {
    return lines.join("\n");
  }
  return lines.map((line) => line.slice(Math.min(minIndent, line.length))).join("\n");
}
function parseLocalFootnotes(text) {
  const lines = String(text ?? "").split("\n");
  const bodyLines = [];
  const definitions = /* @__PURE__ */ new Map();
  const definitionPattern = /^\[\^([A-Za-z0-9_-]+)\]:\s*(.*)$/;
  let index = 0;
  while (index < lines.length) {
    const match = lines[index].match(definitionPattern);
    if (!match) {
      bodyLines.push(lines[index]);
      index++;
      continue;
    }
    const id = match[1];
    const firstLine = match[2] ?? "";
    const definitionLines = [];
    index++;
    if (/^\|[-+]?/.test(firstLine.trim())) {
      while (index < lines.length && !definitionPattern.test(lines[index])) {
        definitionLines.push(lines[index]);
        index++;
      }
    } else {
      if (firstLine.trim()) {
        definitionLines.push(firstLine);
      }
      while (index < lines.length && !definitionPattern.test(lines[index])) {
        definitionLines.push(lines[index]);
        index++;
      }
    }
    const definitionText = dedentLocalFootnoteLines(definitionLines).trim();
    if (definitionText) {
      definitions.set(id, definitionText);
    }
  }
  const orderedFootnotes = [];
  const numbersById = /* @__PURE__ */ new Map();
  const bodyText = bodyLines.join("\n").trimEnd();
  const textWithRefs = bodyText.replace(/\[\^([A-Za-z0-9_-]+)\]/g, (match, id) => {
    const definition = definitions.get(id);
    if (!definition) {
      return match;
    }
    if (!numbersById.has(id)) {
      numbersById.set(id, numbersById.size + 1);
      orderedFootnotes.push({
        id,
        number: numbersById.get(id),
        text: definition,
        collapsed: definition.length > 160 || /(^|\n)```/.test(definition)
      });
    }
    const number = numbersById.get(id);
    const escapedId = escapeHtmlAttribute(id);
    return `<sup class="obsidian-embed-code-file-footnote-ref" data-footnote-id="${escapedId}" tabindex="0">[${number}]</sup>`;
  });
  return {
    text: textWithRefs,
    footnotes: orderedFootnotes
  };
}
function parseLineComments(metaYaml) {
  const comments = metaYaml?.COMMENTS;
  const defaultStyle = normalizeCommentStyle(metaYaml?.COMMENT_STYLE);
  const lineComments = /* @__PURE__ */ new Map();
  if (!comments || typeof comments !== "object" || Array.isArray(comments)) {
    return lineComments;
  }
  Object.entries(comments).forEach(([lineNumberText, comment]) => {
    const lineNumber = Number(lineNumberText);
    if (!Number.isInteger(lineNumber) || lineNumber <= 0) {
      return;
    }
    if (comment && typeof comment === "object" && !Array.isArray(comment)) {
      const text = normalizeCommentText(comment.text ?? comment.comment);
      if (!text) {
        return;
      }
      lineComments.set(lineNumber, {
        style: normalizeCommentStyle(comment.style ?? defaultStyle),
        text
      });
      return;
    }
    const text = normalizeCommentText(comment);
    if (!text) {
      return;
    }
    lineComments.set(lineNumber, {
      style: defaultStyle,
      text
    });
  });
  return lineComments;
}
function splitHighlightedCodeLines(codeElm, lineCount) {
  const lines = codeElm.innerHTML.split("\n");
  while (lines.length < lineCount) {
    lines.push("");
  }
  if (lines.length > lineCount) {
    lines.length = lineCount;
  }
  return lines;
}
function parseBooleanParam(value) {
  if (typeof value === "boolean") {
    return value;
  }
  if (typeof value === "number") {
    return value !== 0;
  }
  if (typeof value === "string") {
    const normalized = value.trim().toLowerCase();
    if (["true", "yes", "1", "on"].includes(normalized)) {
      return true;
    }
    if (["false", "no", "0", "off"].includes(normalized)) {
      return false;
    }
  }
  return null;
}
function parseFontSizeParam(value) {
  if (typeof value === "number" && Number.isFinite(value) && value > 0) {
    return `${value}px`;
  }
  if (typeof value !== "string") {
    return null;
  }
  const fontSize = value.trim();
  return /^(\d+|\d*\.\d+)(px|em|rem|%)$/.test(fontSize) ? fontSize : null;
}
function parseCodeBlockOptions(metaYaml, fallbackWrap) {
  return {
    wrapCodeBlock: parseBooleanParam(metaYaml?.WRAP) ?? fallbackWrap,
    foldable: parseBooleanParam(metaYaml?.FOLDABLE) ?? false,
    collapsed: parseBooleanParam(metaYaml?.COLLAPSED) ?? false,
    fontSize: parseFontSizeParam(metaYaml?.FONT_SIZE)
  };
}

// main.ts
var EMBED_CODE_FILE_RENDER_CLASS = "obsidian-embed-code-file-render";
var MAX_NESTED_EMBED_DEPTH = 1;
var EmbedCodeFile = class extends import_obsidian2.Plugin {
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new EmbedCodeFileSettingTab(this.app, this));
    this.registerMarkdownPostProcessor((element, context) => {
      this.addTitle(element, context);
    });
    const supportedLanguages = this.settings.includedLanguages.split(",");
    supportedLanguages.forEach((l) => {
      console.log(`registering renderer for ${l}`);
      this.registerRenderer(l);
    });
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async registerRenderer(lang) {
    this.registerMarkdownCodeBlockProcessor(`embed-${lang}`, async (meta, el, ctx) => {
      const sourcePath = ctx?.sourcePath || "";
      const embedDepth = this.nestedEmbedDepth(el);
      el.addClass(EMBED_CODE_FILE_RENDER_CLASS);
      if (embedDepth > MAX_NESTED_EMBED_DEPTH) {
        await import_obsidian2.MarkdownRenderer.renderMarkdown(
          "`ERROR: nested embed-code-file depth limit exceeded`",
          el,
          sourcePath,
          this
        );
        return;
      }
      let fullSrc = "";
      let src = "";
      let metaYaml;
      try {
        metaYaml = (0, import_obsidian2.parseYaml)(meta);
      } catch (e) {
        await import_obsidian2.MarkdownRenderer.renderMarkdown("`ERROR: invalid embedding (invalid YAML)`", el, sourcePath, this);
        return;
      }
      let srcPath = metaYaml.PATH;
      if (!srcPath) {
        await import_obsidian2.MarkdownRenderer.renderMarkdown("`ERROR: invalid source path`", el, sourcePath, this);
        return;
      }
      if (srcPath.startsWith("https://") || srcPath.startsWith("http://")) {
        try {
          let httpResp = await (0, import_obsidian2.requestUrl)({ url: srcPath, method: "GET" });
          fullSrc = httpResp.text;
        } catch (e) {
          const errMsg = `\`ERROR: could't fetch '${srcPath}'\``;
          await import_obsidian2.MarkdownRenderer.renderMarkdown(errMsg, el, sourcePath, this);
          return;
        }
      } else if (srcPath.startsWith("vault://")) {
        srcPath = srcPath.replace(/^(vault:\/\/)/, "");
        const tFile = app.vault.getAbstractFileByPath(srcPath);
        if (tFile instanceof import_obsidian2.TFile) {
          fullSrc = await app.vault.read(tFile);
        } else {
          const errMsg = `\`ERROR: could't read file '${srcPath}'\``;
          await import_obsidian2.MarkdownRenderer.renderMarkdown(errMsg, el, sourcePath, this);
          return;
        }
      } else {
        const errMsg = "`ERROR: invalid source path, use 'vault://...' or 'http[s]://...'`";
        await import_obsidian2.MarkdownRenderer.renderMarkdown(errMsg, el, sourcePath, this);
        return;
      }
      let srcLinesNum = [];
      let lineNumbers = [];
      const srcLinesNumString = metaYaml.LINES;
      if (srcLinesNumString) {
        srcLinesNum = analyseSrcLines(srcLinesNumString);
      }
      if (srcLinesNum.length == 0) {
        src = fullSrc;
      } else {
        src = extractSrcLines(fullSrc, srcLinesNum);
      }
      lineNumbers = sourceLineNumbers(fullSrc, srcLinesNum);
      const lineComments = parseLineComments(metaYaml);
      let title = metaYaml.TITLE;
      if (!title) {
        title = srcPath;
      }
      const codeBlockOptions = parseCodeBlockOptions(metaYaml, this.settings.wrapCodeBlock);
      await import_obsidian2.MarkdownRenderer.renderMarkdown("```" + lang + "\n" + src + "\n```", el, sourcePath, this);
      this.applyCodeBlockOptions(el, codeBlockOptions);
      this.addTitleLivePreview(el, title);
      if (!await this.applyLineComments(el, lineNumbers, lineComments, sourcePath)) {
        this.applyLineNumbers(el, lineNumbers);
      }
      this.applyFoldable(el, codeBlockOptions);
    });
  }
  nestedEmbedDepth(el) {
    let depth = 0;
    let current = el.parentElement;
    while (current) {
      if (current.classList?.contains(EMBED_CODE_FILE_RENDER_CLASS)) {
        depth++;
      }
      current = current.parentElement;
    }
    return depth;
  }
  applyCodeBlockOptions(el, options) {
    const pre = el.querySelector("pre");
    if (!pre) {
      return;
    }
    pre.removeClass("obsidian-embed-code-file-wrap-code");
    pre.removeClass("obsidian-embed-code-file-no-wrap-code");
    pre.addClass(options.wrapCodeBlock ? "obsidian-embed-code-file-wrap-code" : "obsidian-embed-code-file-no-wrap-code");
    pre.removeClass("obsidian-embed-code-file-has-font-size");
    pre.style.removeProperty("--obsidian-embed-code-file-font-size");
    if (options.fontSize) {
      pre.addClass("obsidian-embed-code-file-has-font-size");
      pre.style.setProperty("--obsidian-embed-code-file-font-size", options.fontSize);
    }
  }
  applyWrapClass(el) {
    this.applyCodeBlockOptions(el, {
      wrapCodeBlock: this.settings.wrapCodeBlock,
      fontSize: null
    });
  }
  applyLineNumbers(el, lineNumbers) {
    const pre = el.querySelector("pre");
    if (!pre) {
      return;
    }
    pre.querySelectorAll(".obsidian-embed-code-file-line-number-gutter").forEach((x) => x.remove());
    pre.removeClass("obsidian-embed-code-file-line-numbers");
    if (!this.settings.showLineNumbers) {
      return;
    }
    pre.addClass("obsidian-embed-code-file-line-numbers");
    const gutter = document.createElement("div");
    gutter.className = "obsidian-embed-code-file-line-number-gutter";
    lineNumbers.forEach((lineNumber) => {
      const lineNumberEl = document.createElement("div");
      lineNumberEl.className = "obsidian-embed-code-file-line-number";
      if (!lineNumber) {
        lineNumberEl.addClass("is-empty");
      }
      lineNumberEl.appendText(lineNumber);
      gutter.appendChild(lineNumberEl);
    });
    const codeElm = pre.querySelector("code");
    if (codeElm) {
      pre.insertBefore(gutter, codeElm);
    }
  }
  async renderCommentMarkdown(el, text, sourcePath) {
    el.empty();
    const parsed = parseLocalFootnotes(text);
    await import_obsidian2.MarkdownRenderer.renderMarkdown(parsed.text, el, sourcePath, this);
    await this.renderLocalFootnotes(el, parsed, sourcePath);
  }
  async renderLocalFootnotes(el, parsed, sourcePath) {
    if (!parsed.footnotes.length) {
      return;
    }
    const footnotesEl = document.createElement("div");
    footnotesEl.className = "obsidian-embed-code-file-footnotes";
    const renderTasks = [];
    parsed.footnotes.forEach((footnote) => {
      const itemEl = document.createElement("details");
      itemEl.className = "obsidian-embed-code-file-footnote";
      itemEl.dataset.footnoteId = footnote.id;
      itemEl.open = !footnote.collapsed;
      const summaryEl = document.createElement("summary");
      summaryEl.className = "obsidian-embed-code-file-footnote-summary";
      const numberEl = document.createElement("span");
      numberEl.className = "obsidian-embed-code-file-footnote-number";
      numberEl.appendText(String(footnote.number));
      const labelEl = document.createElement("span");
      labelEl.className = "obsidian-embed-code-file-footnote-label";
      labelEl.appendText(footnote.id);
      summaryEl.appendChild(numberEl);
      summaryEl.appendChild(labelEl);
      const footnoteBodyEl = document.createElement("div");
      footnoteBodyEl.className = "obsidian-embed-code-file-footnote-body";
      itemEl.appendChild(summaryEl);
      itemEl.appendChild(footnoteBodyEl);
      footnotesEl.appendChild(itemEl);
      renderTasks.push(() => this.renderCommentMarkdown(footnoteBodyEl, footnote.text, sourcePath));
    });
    el.appendChild(footnotesEl);
    await Promise.all(renderTasks.map((task) => task()));
    this.bindLocalFootnoteInteractions(el);
  }
  bindLocalFootnoteInteractions(el) {
    const refs = Array.from(el.querySelectorAll(".obsidian-embed-code-file-footnote-ref"));
    const footnotes = Array.from(el.querySelectorAll(".obsidian-embed-code-file-footnote"));
    const footnoteById = (id) => footnotes.find((footnote) => footnote.dataset.footnoteId === id);
    const refsById = (id) => refs.filter((ref) => ref.dataset.footnoteId === id);
    const setActive = (id, active) => {
      const footnote = footnoteById(id);
      if (footnote) {
        footnote.toggleClass("is-active", active);
      }
      refsById(id).forEach((ref) => ref.toggleClass("is-active", active));
    };
    refs.forEach((ref) => {
      const id = ref.dataset.footnoteId;
      if (!id) {
        return;
      }
      this.registerDomEvent(ref, "mouseenter", () => setActive(id, true));
      this.registerDomEvent(ref, "mouseleave", () => setActive(id, false));
      this.registerDomEvent(ref, "focus", () => setActive(id, true));
      this.registerDomEvent(ref, "blur", () => setActive(id, false));
      this.registerDomEvent(ref, "click", (event) => {
        event.preventDefault();
        const footnote = footnoteById(id);
        if (!footnote) {
          return;
        }
        footnote.open = true;
        setActive(id, true);
        footnote.scrollIntoView({ block: "nearest", behavior: "smooth" });
        window.setTimeout(() => setActive(id, false), 1200);
      });
    });
    footnotes.forEach((footnote) => {
      const id = footnote.dataset.footnoteId;
      const summaryEl = footnote.querySelector(".obsidian-embed-code-file-footnote-summary");
      if (!id || !summaryEl) {
        return;
      }
      this.registerDomEvent(summaryEl, "mouseenter", () => setActive(id, true));
      this.registerDomEvent(summaryEl, "mouseleave", () => setActive(id, false));
      this.registerDomEvent(summaryEl, "focus", () => setActive(id, true));
      this.registerDomEvent(summaryEl, "blur", () => setActive(id, false));
    });
  }
  async applyLineComments(el, lineNumbers, lineComments, sourcePath) {
    if (!lineComments.size) {
      return false;
    }
    const pre = el.querySelector("pre");
    const codeElm = el.querySelector("pre > code");
    if (!pre || !codeElm) {
      return false;
    }
    pre.querySelectorAll(".obsidian-embed-code-file-line-number-gutter").forEach((x) => x.remove());
    pre.removeClass("obsidian-embed-code-file-line-numbers");
    pre.addClass("obsidian-embed-code-file-commented");
    if (this.settings.showLineNumbers) {
      pre.addClass("obsidian-embed-code-file-line-numbers");
    }
    const codeLines = splitHighlightedCodeLines(codeElm, lineNumbers.length);
    const table = document.createElement("div");
    table.className = "obsidian-embed-code-file-comment-table";
    const renderTasks = [];
    codeLines.forEach((codeLine, index) => {
      const lineNumber = lineNumbers[index] ?? "";
      const lineComment = lineNumber ? lineComments.get(Number(lineNumber)) : null;
      if (lineComment?.style === "above") {
        const commentRow = document.createElement("div");
        commentRow.className = "obsidian-embed-code-file-comment-row obsidian-embed-code-file-comment-above-row";
        const spacer = document.createElement("div");
        spacer.className = "obsidian-embed-code-file-line-number obsidian-embed-code-file-line-number-spacer";
        const commentEl = document.createElement("div");
        commentEl.className = "obsidian-embed-code-file-comment obsidian-embed-code-file-comment-above";
        renderTasks.push(() => this.renderCommentMarkdown(commentEl, lineComment.text, sourcePath));
        commentRow.appendChild(spacer);
        commentRow.appendChild(commentEl);
        table.appendChild(commentRow);
      }
      const lineRow = document.createElement("div");
      lineRow.className = "obsidian-embed-code-file-code-row";
      const gutterEl = document.createElement("div");
      gutterEl.className = "obsidian-embed-code-file-line-number";
      if (!lineNumber) {
        gutterEl.addClass("is-empty");
      }
      const lineNumberEl = document.createElement("span");
      lineNumberEl.className = "obsidian-embed-code-file-line-number-text";
      lineNumberEl.appendText(lineNumber);
      gutterEl.appendChild(lineNumberEl);
      let tooltipEl = null;
      if (lineComment?.style === "icon") {
        const iconEl = document.createElement("span");
        iconEl.className = "obsidian-embed-code-file-comment-icon";
        iconEl.tabIndex = 0;
        iconEl.appendText("!");
        tooltipEl = document.createElement("div");
        tooltipEl.className = "obsidian-embed-code-file-comment-tooltip";
        const tooltipHeaderEl = document.createElement("div");
        tooltipHeaderEl.className = "obsidian-embed-code-file-comment-tooltip-header";
        const tooltipGripEl = document.createElement("span");
        tooltipGripEl.className = "obsidian-embed-code-file-comment-tooltip-grip";
        tooltipGripEl.appendText("::");
        const closeEl = document.createElement("button");
        closeEl.className = "obsidian-embed-code-file-comment-tooltip-close";
        closeEl.type = "button";
        closeEl.setAttribute("aria-label", "Close comment");
        closeEl.appendText("x");
        tooltipHeaderEl.appendChild(tooltipGripEl);
        tooltipHeaderEl.appendChild(closeEl);
        const tooltipContentEl = document.createElement("div");
        tooltipContentEl.className = "obsidian-embed-code-file-comment-tooltip-content";
        tooltipEl.appendChild(tooltipHeaderEl);
        tooltipEl.appendChild(tooltipContentEl);
        renderTasks.push(() => this.renderCommentMarkdown(tooltipContentEl, lineComment.text, sourcePath));
        this.registerDomEvent(iconEl, "click", (event) => {
          event.preventDefault();
          event.stopPropagation();
          this.togglePinnedIconComment(tooltipEl, iconEl, pre);
        });
        this.registerDomEvent(closeEl, "click", (event) => {
          event.preventDefault();
          event.stopPropagation();
          this.unpinIconComment(tooltipEl);
        });
        this.registerDomEvent(tooltipHeaderEl, "pointerdown", (event) => {
          this.startDraggingIconComment(tooltipEl, event);
        });
        gutterEl.appendChild(iconEl);
      }
      const codeLineEl = document.createElement("code");
      codeLineEl.className = "obsidian-embed-code-file-code-line";
      codeLineEl.innerHTML = codeLine || "&nbsp;";
      lineRow.appendChild(gutterEl);
      lineRow.appendChild(codeLineEl);
      if (tooltipEl) {
        lineRow.appendChild(tooltipEl);
      }
      if (lineComment?.style === "inline") {
        const inlineCommentEl = document.createElement("span");
        inlineCommentEl.className = "obsidian-embed-code-file-comment obsidian-embed-code-file-comment-inline";
        renderTasks.push(() => this.renderCommentMarkdown(inlineCommentEl, lineComment.text, sourcePath));
        lineRow.appendChild(inlineCommentEl);
      }
      table.appendChild(lineRow);
    });
    codeElm.replaceWith(table);
    await Promise.all(renderTasks.map((task) => task()));
    return true;
  }
  togglePinnedIconComment(tooltipEl, iconEl, pre) {
    if (tooltipEl.hasClass("is-pinned")) {
      this.unpinIconComment(tooltipEl);
      return;
    }
    const tooltipRect = tooltipEl.getBoundingClientRect();
    const preRect = pre.getBoundingClientRect();
    const fallbackWidth = Math.max(260, Math.min(preRect.width, window.innerWidth - 16));
    const width = Math.max(260, Math.min(tooltipRect.width || fallbackWidth, window.innerWidth - 16));
    const left = Math.max(8, Math.min(tooltipRect.left || preRect.left, window.innerWidth - width - 8));
    const top = Math.max(8, Math.min(tooltipRect.top || iconEl.getBoundingClientRect().bottom + 6, window.innerHeight - 120));
    tooltipEl.pinnedParent = tooltipEl.parentElement;
    tooltipEl.pinnedNextSibling = tooltipEl.nextSibling;
    document.body.appendChild(tooltipEl);
    tooltipEl.addClass("is-pinned");
    tooltipEl.style.left = `${left}px`;
    tooltipEl.style.top = `${top}px`;
    tooltipEl.style.width = `${width}px`;
    tooltipEl.style.height = "";
  }
  unpinIconComment(tooltipEl) {
    tooltipEl.removeClass("is-pinned");
    tooltipEl.style.removeProperty("left");
    tooltipEl.style.removeProperty("top");
    tooltipEl.style.removeProperty("width");
    tooltipEl.style.removeProperty("height");
    if (tooltipEl.pinnedParent) {
      tooltipEl.pinnedParent.insertBefore(tooltipEl, tooltipEl.pinnedNextSibling);
      tooltipEl.pinnedParent = null;
      tooltipEl.pinnedNextSibling = null;
    }
  }
  startDraggingIconComment(tooltipEl, event) {
    if (!tooltipEl.hasClass("is-pinned") || event.button !== 0) {
      return;
    }
    const target = event.target;
    if (target?.closest?.(".obsidian-embed-code-file-comment-tooltip-close")) {
      return;
    }
    event.preventDefault();
    const startRect = tooltipEl.getBoundingClientRect();
    const startX = event.clientX;
    const startY = event.clientY;
    const onMove = (moveEvent) => {
      const nextLeft = Math.max(8, Math.min(startRect.left + moveEvent.clientX - startX, window.innerWidth - startRect.width - 8));
      const nextTop = Math.max(8, Math.min(startRect.top + moveEvent.clientY - startY, window.innerHeight - startRect.height - 8));
      tooltipEl.style.left = `${nextLeft}px`;
      tooltipEl.style.top = `${nextTop}px`;
    };
    const onUp = () => {
      window.removeEventListener("pointermove", onMove);
      window.removeEventListener("pointerup", onUp);
    };
    window.addEventListener("pointermove", onMove);
    window.addEventListener("pointerup", onUp, { once: true });
  }
  addTitleLivePreview(el, title) {
    const codeElm = el.querySelector("pre > code");
    if (!codeElm) {
      return;
    }
    const pre = codeElm.parentElement;
    this.insertTitlePreElement(pre, title);
  }
  applyFoldable(el, options) {
    if (!options.foldable) {
      return;
    }
    const pre = el.querySelector("pre");
    const titleEl = pre?.querySelector(".obsidian-embed-code-file");
    if (!pre || !titleEl) {
      return;
    }
    pre.addClass("obsidian-embed-code-file-foldable");
    titleEl.addClass("obsidian-embed-code-file-fold-toggle");
    titleEl.setAttribute("role", "button");
    titleEl.setAttribute("tabindex", "0");
    const setCollapsed = (collapsed) => {
      pre.toggleClass("obsidian-embed-code-file-collapsed", collapsed);
      titleEl.setAttribute("aria-expanded", String(!collapsed));
    };
    setCollapsed(options.collapsed);
    const toggle = () => setCollapsed(!pre.hasClass("obsidian-embed-code-file-collapsed"));
    this.registerDomEvent(titleEl, "click", toggle);
    this.registerDomEvent(titleEl, "keydown", (evt) => {
      if (evt.key !== "Enter" && evt.key !== " ") {
        return;
      }
      evt.preventDefault();
      toggle();
    });
  }
  addTitle(el, context) {
    let codeElm = el.querySelector("pre > code");
    if (!codeElm) {
      return;
    }
    const pre = codeElm.parentElement;
    const codeSection = context.getSectionInfo(pre);
    if (!codeSection) {
      return;
    }
    const view = app.workspace.getActiveViewOfType(import_obsidian2.MarkdownView);
    if (!view) {
      return;
    }
    const num = codeSection.lineStart;
    const codeBlockFirstLine = view.editor.getLine(num);
    let matchTitle = codeBlockFirstLine.match(/TITLE:\s*"([^"]*)"/i);
    if (matchTitle == null) {
      return;
    }
    const title = matchTitle[1];
    if (title == "") {
      return;
    }
    this.applyWrapClass(el);
    this.insertTitlePreElement(pre, title);
  }
  insertTitlePreElement(pre, title) {
    pre.querySelectorAll(".obsidian-embed-code-file").forEach((x) => x.remove());
    let titleElement = document.createElement("pre");
    titleElement.appendText(title);
    titleElement.className = "obsidian-embed-code-file";
    titleElement.style.color = this.settings.titleFontColor;
    titleElement.style.backgroundColor = this.settings.titleBackgroundColor;
    pre.prepend(titleElement);
  }
};

/* nosourcemap */
