/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target, mod));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => EmbedCodeFile
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");

// settings.ts
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  includedLanguages: "c,cpp,java,python,go,ruby,javascript,js,typescript,ts,shell,sh,bash",
  titleBackgroundColor: "#00000020",
  titleFontColor: "",
  wrapCodeBlock: false,
  showLineNumbers: false
};
var EmbedCodeFileSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app2, plugin) {
    super(app2, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Embed Code File Settings" });
    new import_obsidian.Setting(containerEl).setName("Included Languages").setDesc("Comma separated list of included languages.").addText((text) => text.setPlaceholder("Comma separated list").setValue(this.plugin.settings.includedLanguages).onChange(async (value) => {
      this.plugin.settings.includedLanguages = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Font color of title").addText((text) => text.setPlaceholder("Enter a color").setValue(this.plugin.settings.titleFontColor).onChange(async (value) => {
      this.plugin.settings.titleFontColor = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Background color of title").addText((text) => text.setPlaceholder("#00000020").setValue(this.plugin.settings.titleBackgroundColor).onChange(async (value) => {
      this.plugin.settings.titleBackgroundColor = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Wrap code blocks").setDesc("With this option enabled, embedded code files will wrap long lines.").addToggle((toggle) => toggle.setValue(this.plugin.settings.wrapCodeBlock).onChange(async (value) => {
      this.plugin.settings.wrapCodeBlock = value;
      await this.plugin.saveSettings();
      const view = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
      view?.previewMode.rerender(true);
    }));
    new import_obsidian.Setting(containerEl).setName("Show line numbers").setDesc("With this option enabled, embedded code files will show original source line numbers.").addToggle((toggle) => toggle.setValue(this.plugin.settings.showLineNumbers).onChange(async (value) => {
      this.plugin.settings.showLineNumbers = value;
      await this.plugin.saveSettings();
      const view = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
      view?.previewMode.rerender(true);
    }));
  }
};

// utils.ts
var import_path = __toESM(require("path"));
function analyseSrcLines(str) {
  str = str.replace(/\s*/g, "");
  const result = [];
  let strs = str.split(",");
  strs.forEach((it) => {
    if (/\w+-\w+/.test(it)) {
      let left = Number(it.split("-")[0]);
      let right = Number(it.split("-")[1]);
      for (let i = left; i <= right; i++) {
        result.push(i);
      }
      result.push(0);
    } else {
      result.push(Number(it));
      result.push(0);
    }
  });
  return result;
}
function extractSrcLines(fullSrc, srcLinesNum) {
  let src = "";
  const fullSrcLines = fullSrc.split("\n");
  const fullSrcLinesLen = fullSrcLines.length;
  srcLinesNum.forEach((lineNum, index, arr) => {
    if (lineNum > fullSrcLinesLen) {
      arr.splice(index, 1);
    }
  });
  srcLinesNum.forEach((lineNum, index, arr) => {
    if (lineNum == 0 && arr[index - 1] == 0) {
      arr.splice(index, 1);
    }
  });
  srcLinesNum.forEach((lineNum, index) => {
    if (lineNum > fullSrcLinesLen) {
      return;
    }
    if (index == srcLinesNum.length - 1 && lineNum == 0 && srcLinesNum[index - 1] == fullSrcLinesLen) {
      return;
    }
    if (index == 0 && lineNum != 1) {
      src = "...\n" + fullSrcLines[lineNum - 1];
      return;
    }
    if (lineNum == 0) {
      src = src + "\n...";
      return;
    }
    if (index == 0) {
      src = fullSrcLines[lineNum - 1];
    } else {
      src = src + "\n" + fullSrcLines[lineNum - 1];
    }
  });
  return src;
}
function sourceLineNumbers(fullSrc, srcLinesNum) {
  const fullSrcLinesLen = fullSrc.split("\n").length;
  if (srcLinesNum.length == 0) {
    return Array.from({ length: fullSrcLinesLen }, (_, index) => String(index + 1));
  }
  const compactLineNums = [];
  srcLinesNum.forEach((lineNum) => {
    if (lineNum > fullSrcLinesLen) {
      return;
    }
    if (lineNum == 0 && compactLineNums[compactLineNums.length - 1] == 0) {
      return;
    }
    compactLineNums.push(lineNum);
  });
  const lineNumbers = [];
  compactLineNums.forEach((lineNum, index) => {
    if (index == compactLineNums.length - 1 && lineNum == 0 && compactLineNums[index - 1] == fullSrcLinesLen) {
      return;
    }
    if (index == 0 && lineNum != 1) {
      lineNumbers.push("");
      lineNumbers.push(String(lineNum));
      return;
    }
    if (lineNum == 0) {
      lineNumbers.push("");
      return;
    }
    lineNumbers.push(String(lineNum));
  });
  return lineNumbers;
}
function normalizeCommentStyle(style) {
  const value = String(style ?? "above").trim().toLowerCase();
  return ["above", "inline", "icon"].includes(value) ? value : "above";
}
function normalizeCommentText(comment) {
  if (Array.isArray(comment)) {
    return comment.map((item) => normalizeCommentText(item)).join("\n");
  }
  if (comment == null) {
    return "";
  }
  return String(comment);
}
function parseLineComments(metaYaml) {
  const comments = metaYaml?.COMMENTS;
  const defaultStyle = normalizeCommentStyle(metaYaml?.COMMENT_STYLE);
  const lineComments = /* @__PURE__ */ new Map();
  if (!comments || typeof comments !== "object" || Array.isArray(comments)) {
    return lineComments;
  }
  Object.entries(comments).forEach(([lineNumberText, comment]) => {
    const lineNumber = Number(lineNumberText);
    if (!Number.isInteger(lineNumber) || lineNumber <= 0) {
      return;
    }
    if (comment && typeof comment === "object" && !Array.isArray(comment)) {
      const text = normalizeCommentText(comment.text ?? comment.comment);
      if (!text) {
        return;
      }
      lineComments.set(lineNumber, {
        style: normalizeCommentStyle(comment.style ?? defaultStyle),
        text
      });
      return;
    }
    const text = normalizeCommentText(comment);
    if (!text) {
      return;
    }
    lineComments.set(lineNumber, {
      style: defaultStyle,
      text
    });
  });
  return lineComments;
}
function splitHighlightedCodeLines(codeElm, lineCount) {
  const lines = codeElm.innerHTML.split("\n");
  while (lines.length < lineCount) {
    lines.push("");
  }
  if (lines.length > lineCount) {
    lines.length = lineCount;
  }
  return lines;
}

// main.ts
var EmbedCodeFile = class extends import_obsidian2.Plugin {
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new EmbedCodeFileSettingTab(this.app, this));
    this.registerMarkdownPostProcessor((element, context) => {
      this.addTitle(element, context);
    });
    const supportedLanguages = this.settings.includedLanguages.split(",");
    supportedLanguages.forEach((l) => {
      console.log(`registering renderer for ${l}`);
      this.registerRenderer(l);
    });
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async registerRenderer(lang) {
    this.registerMarkdownCodeBlockProcessor(`embed-${lang}`, async (meta, el, ctx) => {
      let fullSrc = "";
      let src = "";
      let metaYaml;
      try {
        metaYaml = (0, import_obsidian2.parseYaml)(meta);
      } catch (e) {
        await import_obsidian2.MarkdownRenderer.renderMarkdown("`ERROR: invalid embedding (invalid YAML)`", el, "", this);
        return;
      }
      let srcPath = metaYaml.PATH;
      if (!srcPath) {
        await import_obsidian2.MarkdownRenderer.renderMarkdown("`ERROR: invalid source path`", el, "", this);
        return;
      }
      if (srcPath.startsWith("https://") || srcPath.startsWith("http://")) {
        try {
          let httpResp = await (0, import_obsidian2.requestUrl)({ url: srcPath, method: "GET" });
          fullSrc = httpResp.text;
        } catch (e) {
          const errMsg = `\`ERROR: could't fetch '${srcPath}'\``;
          await import_obsidian2.MarkdownRenderer.renderMarkdown(errMsg, el, "", this);
          return;
        }
      } else if (srcPath.startsWith("vault://")) {
        srcPath = srcPath.replace(/^(vault:\/\/)/, "");
        const tFile = app.vault.getAbstractFileByPath(srcPath);
        if (tFile instanceof import_obsidian2.TFile) {
          fullSrc = await app.vault.read(tFile);
        } else {
          const errMsg = `\`ERROR: could't read file '${srcPath}'\``;
          await import_obsidian2.MarkdownRenderer.renderMarkdown(errMsg, el, "", this);
          return;
        }
      } else {
        const errMsg = "`ERROR: invalid source path, use 'vault://...' or 'http[s]://...'`";
        await import_obsidian2.MarkdownRenderer.renderMarkdown(errMsg, el, "", this);
        return;
      }
      let srcLinesNum = [];
      let lineNumbers = [];
      const srcLinesNumString = metaYaml.LINES;
      if (srcLinesNumString) {
        srcLinesNum = analyseSrcLines(srcLinesNumString);
      }
      if (srcLinesNum.length == 0) {
        src = fullSrc;
      } else {
        src = extractSrcLines(fullSrc, srcLinesNum);
      }
      lineNumbers = sourceLineNumbers(fullSrc, srcLinesNum);
      const lineComments = parseLineComments(metaYaml);
      let title = metaYaml.TITLE;
      if (!title) {
        title = srcPath;
      }
      await import_obsidian2.MarkdownRenderer.renderMarkdown("```" + lang + "\n" + src + "\n```", el, "", this);
      this.applyWrapClass(el);
      this.addTitleLivePreview(el, title);
      if (!await this.applyLineComments(el, lineNumbers, lineComments)) {
        this.applyLineNumbers(el, lineNumbers);
      }
    });
  }
  applyWrapClass(el) {
    const pre = el.querySelector("pre");
    if (!pre) {
      return;
    }
    pre.removeClass("obsidian-embed-code-file-wrap-code");
    pre.removeClass("obsidian-embed-code-file-no-wrap-code");
    pre.addClass(this.settings.wrapCodeBlock ? "obsidian-embed-code-file-wrap-code" : "obsidian-embed-code-file-no-wrap-code");
  }
  applyLineNumbers(el, lineNumbers) {
    const pre = el.querySelector("pre");
    if (!pre) {
      return;
    }
    pre.querySelectorAll(".obsidian-embed-code-file-line-number-gutter").forEach((x) => x.remove());
    pre.removeClass("obsidian-embed-code-file-line-numbers");
    if (!this.settings.showLineNumbers) {
      return;
    }
    pre.addClass("obsidian-embed-code-file-line-numbers");
    const gutter = document.createElement("div");
    gutter.className = "obsidian-embed-code-file-line-number-gutter";
    lineNumbers.forEach((lineNumber) => {
      const lineNumberEl = document.createElement("div");
      lineNumberEl.className = "obsidian-embed-code-file-line-number";
      if (!lineNumber) {
        lineNumberEl.addClass("is-empty");
      }
      lineNumberEl.appendText(lineNumber);
      gutter.appendChild(lineNumberEl);
    });
    const codeElm = pre.querySelector("code");
    if (codeElm) {
      pre.insertBefore(gutter, codeElm);
    }
  }
  async renderCommentMarkdown(el, text) {
    el.empty();
    await import_obsidian2.MarkdownRenderer.renderMarkdown(text, el, "", this);
  }
  async applyLineComments(el, lineNumbers, lineComments) {
    if (!lineComments.size) {
      return false;
    }
    const pre = el.querySelector("pre");
    const codeElm = el.querySelector("pre > code");
    if (!pre || !codeElm) {
      return false;
    }
    pre.querySelectorAll(".obsidian-embed-code-file-line-number-gutter").forEach((x) => x.remove());
    pre.removeClass("obsidian-embed-code-file-line-numbers");
    pre.addClass("obsidian-embed-code-file-commented");
    if (this.settings.showLineNumbers) {
      pre.addClass("obsidian-embed-code-file-line-numbers");
    }
    const codeLines = splitHighlightedCodeLines(codeElm, lineNumbers.length);
    const table = document.createElement("div");
    table.className = "obsidian-embed-code-file-comment-table";
    const renderTasks = [];
    codeLines.forEach((codeLine, index) => {
      const lineNumber = lineNumbers[index] ?? "";
      const lineComment = lineNumber ? lineComments.get(Number(lineNumber)) : null;
      if (lineComment?.style === "above") {
        const commentRow = document.createElement("div");
        commentRow.className = "obsidian-embed-code-file-comment-row obsidian-embed-code-file-comment-above-row";
        const spacer = document.createElement("div");
        spacer.className = "obsidian-embed-code-file-line-number obsidian-embed-code-file-line-number-spacer";
        const commentEl = document.createElement("div");
        commentEl.className = "obsidian-embed-code-file-comment obsidian-embed-code-file-comment-above";
        renderTasks.push(() => this.renderCommentMarkdown(commentEl, lineComment.text));
        commentRow.appendChild(spacer);
        commentRow.appendChild(commentEl);
        table.appendChild(commentRow);
      }
      const lineRow = document.createElement("div");
      lineRow.className = "obsidian-embed-code-file-code-row";
      const gutterEl = document.createElement("div");
      gutterEl.className = "obsidian-embed-code-file-line-number";
      if (!lineNumber) {
        gutterEl.addClass("is-empty");
      }
      const lineNumberEl = document.createElement("span");
      lineNumberEl.className = "obsidian-embed-code-file-line-number-text";
      lineNumberEl.appendText(lineNumber);
      gutterEl.appendChild(lineNumberEl);
      if (lineComment?.style === "icon") {
        const iconEl = document.createElement("span");
        iconEl.className = "obsidian-embed-code-file-comment-icon";
        iconEl.setAttribute("aria-label", lineComment.text);
        iconEl.appendText("!");
        const tooltipEl = document.createElement("span");
        tooltipEl.className = "obsidian-embed-code-file-comment-tooltip";
        renderTasks.push(() => this.renderCommentMarkdown(tooltipEl, lineComment.text));
        iconEl.appendChild(tooltipEl);
        gutterEl.appendChild(iconEl);
      }
      const codeLineEl = document.createElement("code");
      codeLineEl.className = "obsidian-embed-code-file-code-line";
      codeLineEl.innerHTML = codeLine || "&nbsp;";
      lineRow.appendChild(gutterEl);
      lineRow.appendChild(codeLineEl);
      if (lineComment?.style === "inline") {
        const inlineCommentEl = document.createElement("span");
        inlineCommentEl.className = "obsidian-embed-code-file-comment obsidian-embed-code-file-comment-inline";
        renderTasks.push(() => this.renderCommentMarkdown(inlineCommentEl, lineComment.text));
        lineRow.appendChild(inlineCommentEl);
      }
      table.appendChild(lineRow);
    });
    codeElm.replaceWith(table);
    await Promise.all(renderTasks.map((task) => task()));
    return true;
  }
  addTitleLivePreview(el, title) {
    const codeElm = el.querySelector("pre > code");
    if (!codeElm) {
      return;
    }
    const pre = codeElm.parentElement;
    this.insertTitlePreElement(pre, title);
  }
  addTitle(el, context) {
    let codeElm = el.querySelector("pre > code");
    if (!codeElm) {
      return;
    }
    const pre = codeElm.parentElement;
    const codeSection = context.getSectionInfo(pre);
    if (!codeSection) {
      return;
    }
    const view = app.workspace.getActiveViewOfType(import_obsidian2.MarkdownView);
    if (!view) {
      return;
    }
    const num = codeSection.lineStart;
    const codeBlockFirstLine = view.editor.getLine(num);
    let matchTitle = codeBlockFirstLine.match(/TITLE:\s*"([^"]*)"/i);
    if (matchTitle == null) {
      return;
    }
    const title = matchTitle[1];
    if (title == "") {
      return;
    }
    this.applyWrapClass(el);
    this.insertTitlePreElement(pre, title);
  }
  insertTitlePreElement(pre, title) {
    pre.querySelectorAll(".obsidian-embed-code-file").forEach((x) => x.remove());
    let titleElement = document.createElement("pre");
    titleElement.appendText(title);
    titleElement.className = "obsidian-embed-code-file";
    titleElement.style.color = this.settings.titleFontColor;
    titleElement.style.backgroundColor = this.settings.titleBackgroundColor;
    pre.prepend(titleElement);
  }
};

/* nosourcemap */
